# Generated by Django 2.2.12 on 2020-05-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='commodity',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='commodity_orders', to='commodity.Commodity', verbose_name='商品'),
        ),
    ]
