# Generated by Django 2.2.12 on 2020-05-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='商品名称'),
            preserve_default=False,
        ),
    ]
